# uncompyle6 version 3.9.3
# Python bytecode version base 3.6 (3379)
# Decompiled from: Python 3.12.3 (main, Jan  8 2026, 11:30:50) [GCC 13.3.0]
# Embedded file name: /firmware/components/odin/src/odin/core/isotp/constants.py
TP_LINK_MAX_LEN = 8
SIZE_MAX = 4294967295L
SINGLE_FRAME_HEADER_LEN = 1
FIRST_FRAME_HEADER_LEN = 2
CONSECUTIVE_FRAME_HEADER_LEN = 1
FLOW_CONTROL_FRAME_HEADER_LEN = 3
SINGLE_FRAME_MAX_LEN = TP_LINK_MAX_LEN - SINGLE_FRAME_HEADER_LEN
FIRST_FRAME_DATA_LEN = TP_LINK_MAX_LEN - FIRST_FRAME_HEADER_LEN
CONSECUTIVE_FRAME_DATA_LEN = TP_LINK_MAX_LEN - CONSECUTIVE_FRAME_HEADER_LEN
TIMEOUT_MULTIPLIER = 1.5
N_AS_TIMEOUT = 1.0 * TIMEOUT_MULTIPLIER
N_AR_TIMEOUT = 1.0 * TIMEOUT_MULTIPLIER
N_BS_TIMEOUT = 1.0 * TIMEOUT_MULTIPLIER
N_CR_TIMEOUT = 1.0 * TIMEOUT_MULTIPLIER
UDS_SERVER_ENHANCED_RESPONSE_TIME = 5.0

# okay decompiling /root/downloads/old-firmware/opt/odin/odin_extracted/out00-PYZ.pyz_extracted/odin/core/isotp/constants.pyc
